import men from "@/src/app/components/assets/images/products/Men.png";
import { StaticImageData } from "next/image";

interface PromotionProduct {
    id: number;
    name: string;
    image: StaticImageData;
    price: number;
    oldPrice: number | null;
    rating: number;
    reviews: number;
    isWishlisted?: boolean;
}

export const PromotionsData: PromotionProduct [] = [
    {
        id: 1,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 5,
        reviews: 1,
        isWishlisted: false,
    },
    {
        id: 2,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true, // Matches the red heart in your screenshot
    },
    {
        id: 3,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 5,
        reviews: 2,
        isWishlisted: false,
    },
    {
        id: 4,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 0,
        reviews: 0,
        isWishlisted: false,
    },
    {
        id: 5,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 5,
        reviews: 1,
        isWishlisted: false,
    },
    {
        id: 6,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 7,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 8,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 9,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 10,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 11,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 12,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 13,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 14,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 15,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 16,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 17,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 18,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    },
    {
        id: 19,
        name: "The north coat",
        image: men,
        price: 260,
        oldPrice: 360,
        rating: 3,
        reviews: 2,
        isWishlisted: true,
    }

];